import ThemeRegistry from '@/utils/ThemeRegistry'
import AppBar from '@/components/AppBar'
import type { Metadata } from 'next'
import { getServerSession } from 'next-auth'
import BottomNavigation from '@/components/BottomNavigation'
import { authOptions } from './api/auth/[...nextauth]/route'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const session = await getServerSession(authOptions)

  return (
    <html lang="en">
      <body>
        <ThemeRegistry options={{ key: 'mui' }}>
          <AppBar
            signedIn={session?.user ? true : false}
            sx={{
              bgcolor: 'primary.main',
              color: 'primary.contrastText',
            }}
          />
          {children}
          <BottomNavigation />
        </ThemeRegistry>
      </body>
    </html>
  )
}
